[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'ds-test/=lib/universal-router/solmate/lib/ds-test/src/',
    '@uniswap/=lib/universal-router/node_modules/@uniswap/',
    'forge-gas-snapshot/=lib/permit2/lib/forge-gas-snapshot/src/',
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts/=lib/permit2/lib/openzeppelin-contracts/',
    'permit2/=lib/permit2/',
    'solmate/=lib/universal-router/lib/solmate/',
    'universal-router/=lib/universal-router/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
