[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'ds-test/=lib/universal-router/solmate/lib/ds-test/src/',
    'forge-gas-snapshot/=lib/permit2/lib/forge-gas-snapshot/src/',
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts/=lib/permit2/lib/openzeppelin-contracts/',
    'permit2/=lib/permit2/',
    'solmate/=lib/universal-router/lib/solmate/',
    'universal-router/=lib/universal-router/',
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    'v4-periphery/=/Users/arturohaas/WebstormProjects/kipu-bank-v3/KipuBankV3/lib/v4-periphery/',
    '@uniswap/v3-core/=lib/v3-core/',
    '@uniswap/v2-core/=lib/v2-core/',
    "@uniswap/v4-core/=lib/v4-core/",
    "v4-core/=lib/v4-core/",
]

solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options